[install]
# Only install package versions published at least 3 days ago
minimumReleaseAge = 259200
# Exclude trusted packages from the age gate
minimumReleaseAgeExcludes = ["@base-ui-components/react", "@base-ui-components/utils"]
linker = "isolated"
